version: "3"

services:
  app:
    build:
      context: .
      dockerfile: App.Dockerfile
    ports:
      - ${APP_PORT}:8080
    volumes:
      - ./:/app
    command: go run .
    env_file: .env
    depends_on:
      - database

  database:
    build:
      context: .
      dockerfile: Database.Dockerfile
    ports:
      - ${DB_PORT}:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - TZ=America/Sao_Paulo
    volumes:
      - ./db/dump/:/docker-entrypoint-initdb.d/
    env_file: .env
    restart: always
