version: "3"

services:
  app:
    build: .
    ports:
      - ${APP_PORT}:8080
    volumes:
      - ./:/app
    command: go run .
    env_file: .env
    depends_on:
      - database

  database:
    image: mysql:5.7
    ports:
      - ${DB_PORT}:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    env_file: .env
    restart: always
